global:
  scrape_interval: 5s  # Frequenza di raccolta 

scrape_configs:
  # Configurazione per MQTT Exporter
  - job_name: 'mqtt-exporter'  
    static_configs:
      - targets: ['mqtt-exporter:9101']  

  # Configurazione per OPC-UA Exporter
  - job_name: 'opcua-exporter'  
    static_configs:
      - targets: ['opcua-exporter:9102']  
      
  - job_name: 'opcua-exporter2'  
    static_configs:
    - targets: ['opcua-exporter2:9102']  


remote_write:
  - url: "http://mimir:9009/api/v1/push"  


